name: Deploy Landing Page

on:
  push:
    branches:
      - main
    paths:
      - 'landing-page/**'
      - '.github/workflows/deploy-app.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install Dependencies
        working-directory: ./landing-page
        run: npm install
        
      - name: Build
        working-directory: ./landing-page
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./landing-page/dist
